/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/monsters.glb -o src/components/Monster/Monsters.jsx -r public
Author: quaternius (https://sketchfab.com/quaternius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultimate-monsters-pack-fd72e114d119488da71fe3a16f216c4f
Title: Ultimate Monsters Pack
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Monsters(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/monsters.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(()=>{
	if(actions){
		actions['Take 01'].play()
	}
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} position={[-27,0,0]}>
          <group name="Root">
            <group name="CharacterArmature049" position={[4.579, -17.621, 0]} rotation={[0, 0, -0.264]} scale={0.651}>
              <primitive object={nodes.CharacterArmature049_rootJoint} />
              <group name="Yeti_Blob001" />
              <skinnedMesh name="Yeti_Blob001_0" geometry={nodes.Yeti_Blob001_0.geometry} material={materials.Chicken_Main} skeleton={nodes.Yeti_Blob001_0.skeleton} />
              <skinnedMesh name="Yeti_Blob001_1" geometry={nodes.Yeti_Blob001_1.geometry} material={materials.Yeti_Secondary} skeleton={nodes.Yeti_Blob001_1.skeleton} />
              <skinnedMesh name="Yeti_Blob001_2" geometry={nodes.Yeti_Blob001_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Yeti_Blob001_2.skeleton} />
              <skinnedMesh name="Yeti_Blob001_3" geometry={nodes.Yeti_Blob001_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Yeti_Blob001_3.skeleton} />
              <skinnedMesh name="Yeti_Blob001_4" geometry={nodes.Yeti_Blob001_4.geometry} material={materials.Pink_Secondary} skeleton={nodes.Yeti_Blob001_4.skeleton} />
              <skinnedMesh name="Yeti_Blob001_5" geometry={nodes.Yeti_Blob001_5.geometry} material={materials['Teeth.002']} skeleton={nodes.Yeti_Blob001_5.skeleton} />
            </group>
            <group name="CharacterArmature048" position={[0.624, -18.285, 0]} rotation={[0, 0, -0.439]} scale={0.702}>
              <primitive object={nodes.CharacterArmature048_rootJoint} />
              <group name="Wizard_Blob" />
              <group name="Wizard_Blob001" />
              <skinnedMesh name="Wizard_Blob_0" geometry={nodes.Wizard_Blob_0.geometry} material={materials.Wizard_Main} skeleton={nodes.Wizard_Blob_0.skeleton} />
              <skinnedMesh name="Wizard_Blob_1" geometry={nodes.Wizard_Blob_1.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Wizard_Blob_1.skeleton} />
              <skinnedMesh name="Wizard_Blob001_0" geometry={nodes.Wizard_Blob001_0.geometry} material={materials.Wizard_Main} skeleton={nodes.Wizard_Blob001_0.skeleton} />
              <skinnedMesh name="Wizard_Blob001_1" geometry={nodes.Wizard_Blob001_1.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Wizard_Blob001_1.skeleton} />
              <skinnedMesh name="Wizard_Blob001_2" geometry={nodes.Wizard_Blob001_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Wizard_Blob001_2.skeleton} />
              <skinnedMesh name="Wizard_Blob001_3" geometry={nodes.Wizard_Blob001_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Wizard_Blob001_3.skeleton} />
            </group>
            <group name="CharacterArmature047" position={[0.623, -0.466, -0.03]} scale={1.032}>
              <primitive object={nodes.CharacterArmature047_rootJoint} />
              <group name="Pink_Blob" />
              <group name="Pink_Blob001" />
              <skinnedMesh name="Pink_Blob_0" geometry={nodes.Pink_Blob_0.geometry} material={materials.Squidle_Main} skeleton={nodes.Pink_Blob_0.skeleton} />
              <skinnedMesh name="Pink_Blob_1" geometry={nodes.Pink_Blob_1.geometry} material={materials.Pink_Secondary} skeleton={nodes.Pink_Blob_1.skeleton} />
              <skinnedMesh name="Pink_Blob001_0" geometry={nodes.Pink_Blob001_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Pink_Blob001_0.skeleton} />
              <skinnedMesh name="Pink_Blob001_1" geometry={nodes.Pink_Blob001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Pink_Blob001_1.skeleton} />
            </group>
            <group name="CharacterArmature046" position={[3.402, -23.857, 0]} rotation={[0, 0, -0.344]} scale={0.825}>
              <primitive object={nodes.CharacterArmature046_rootJoint} />
              <group name="Pigeon_Blob_Eyes" position={[-0.548, 1.532, 0]} />
              <skinnedMesh name="Pigeon_Blob_Eyes_0" geometry={nodes.Pigeon_Blob_Eyes_0.geometry} material={materials['Pigeon_Main.001']} skeleton={nodes.Pigeon_Blob_Eyes_0.skeleton} />
              <skinnedMesh name="Pigeon_Blob_Eyes_1" geometry={nodes.Pigeon_Blob_Eyes_1.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Pigeon_Blob_Eyes_1.skeleton} />
              <skinnedMesh name="Pigeon_Blob_Eyes_2" geometry={nodes.Pigeon_Blob_Eyes_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Pigeon_Blob_Eyes_2.skeleton} />
              <skinnedMesh name="Pigeon_Blob_Eyes_3" geometry={nodes.Pigeon_Blob_Eyes_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Pigeon_Blob_Eyes_3.skeleton} />
            </group>
            <group name="CharacterArmature045" position={[-10.151, -12.673, 0]} rotation={[0, 0, 0.113]} scale={0.778}>
              <primitive object={nodes.CharacterArmature045_rootJoint} />
              <group name="Orc_Blob" scale={1.608} />
              <skinnedMesh name="Orc_Blob_0" geometry={nodes.Orc_Blob_0.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Orc_Blob_0.skeleton} />
              <skinnedMesh name="Orc_Blob_1" geometry={nodes.Orc_Blob_1.geometry} material={materials.Squidle_Main} skeleton={nodes.Orc_Blob_1.skeleton} />
              <skinnedMesh name="Orc_Blob_2" geometry={nodes.Orc_Blob_2.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Orc_Blob_2.skeleton} />
              <skinnedMesh name="Orc_Blob_3" geometry={nodes.Orc_Blob_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Orc_Blob_3.skeleton} />
              <skinnedMesh name="Orc_Blob_4" geometry={nodes.Orc_Blob_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Orc_Blob_4.skeleton} />
              <skinnedMesh name="Orc_Blob_5" geometry={nodes.Orc_Blob_5.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Orc_Blob_5.skeleton} />
              <skinnedMesh name="Orc_Blob_6" geometry={nodes.Orc_Blob_6.geometry} material={materials.Pink_Secondary} skeleton={nodes.Orc_Blob_6.skeleton} />
            </group>
            <RigidBody>
			<group name="CharacterArmature044" position={[-3.575, -24.012, 0]} rotation={[0, 0, 0.113]} scale={0.724}>
              <primitive object={nodes.CharacterArmature044_rootJoint} />
              <group name="Ninja_Blob001" />
              <skinnedMesh name="Ninja_Blob001_0" geometry={nodes.Ninja_Blob001_0.geometry} material={materials['Ninja_Main.001']} skeleton={nodes.Ninja_Blob001_0.skeleton} />
              <skinnedMesh name="Ninja_Blob001_1" geometry={nodes.Ninja_Blob001_1.geometry} material={materials.Ninja_Secondary} skeleton={nodes.Ninja_Blob001_1.skeleton} />
              <skinnedMesh name="Ninja_Blob001_2" geometry={nodes.Ninja_Blob001_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Ninja_Blob001_2.skeleton} />
              <skinnedMesh name="Ninja_Blob001_3" geometry={nodes.Ninja_Blob001_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Ninja_Blob001_3.skeleton} />
              <skinnedMesh name="Ninja_Blob001_4" geometry={nodes.Ninja_Blob001_4.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Ninja_Blob001_4.skeleton} />
            </group>
			</RigidBody>
            <group name="CharacterArmature043" position={[-6.272, -18.613, 0]} rotation={[0, 0, 0.207]} scale={0.558}>
              <primitive object={nodes.CharacterArmature043_rootJoint} />
              <group name="Mushnub_Evolved" />
              <group name="Mushnub_Evolved001" />
              <group name="Mushnub_Evolved002" />
              <skinnedMesh name="Mushnub_Evolved_0" geometry={nodes.Mushnub_Evolved_0.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Mushnub_Evolved_0.skeleton} />
              <skinnedMesh name="Mushnub_Evolved_1" geometry={nodes.Mushnub_Evolved_1.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Mushnub_Evolved_1.skeleton} />
              <skinnedMesh name="Mushnub_Evolved_2" geometry={nodes.Mushnub_Evolved_2.geometry} material={materials.Pink_Secondary} skeleton={nodes.Mushnub_Evolved_2.skeleton} />
              <skinnedMesh name="Mushnub_Evolved_3" geometry={nodes.Mushnub_Evolved_3.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Mushnub_Evolved_3.skeleton} />
              <skinnedMesh name="Mushnub_Evolved001_0" geometry={nodes.Mushnub_Evolved001_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Mushnub_Evolved001_0.skeleton} />
              <skinnedMesh name="Mushnub_Evolved001_1" geometry={nodes.Mushnub_Evolved001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Mushnub_Evolved001_1.skeleton} />
              <skinnedMesh name="Mushnub_Evolved002_0" geometry={nodes.Mushnub_Evolved002_0.geometry} material={materials.Pink_Secondary} skeleton={nodes.Mushnub_Evolved002_0.skeleton} />
              <skinnedMesh name="Mushnub_Evolved002_1" geometry={nodes.Mushnub_Evolved002_1.geometry} material={materials['Teeth.002']} skeleton={nodes.Mushnub_Evolved002_1.skeleton} />
            </group>
            <group name="CharacterArmature042" position={[6.94, -23.398, 0]} rotation={[0, 0, -0.145]} scale={0.571}>
              <primitive object={nodes.CharacterArmature042_rootJoint} />
              <group name="GreenSpiky_Blob" />
              <group name="GreenSpiky_Blob002" />
              <skinnedMesh name="GreenSpiky_Blob_0" geometry={nodes.GreenSpiky_Blob_0.geometry} material={materials.Green_Main} skeleton={nodes.GreenSpiky_Blob_0.skeleton} />
              <skinnedMesh name="GreenSpiky_Blob_1" geometry={nodes.GreenSpiky_Blob_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.GreenSpiky_Blob_1.skeleton} />
              <skinnedMesh name="GreenSpiky_Blob002_0" geometry={nodes.GreenSpiky_Blob002_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.GreenSpiky_Blob002_0.skeleton} />
              <skinnedMesh name="GreenSpiky_Blob002_1" geometry={nodes.GreenSpiky_Blob002_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.GreenSpiky_Blob002_1.skeleton} />
            </group>
            <group name="CharacterArmature041" position={[8.211, -24.411, 0]} rotation={[0, 0, -0.198]} scale={0.64}>
              <primitive object={nodes.CharacterArmature041_rootJoint} />
              <group name="Green_Blob" />
              <group name="Green_Blob001" />
              <skinnedMesh name="Green_Blob_0" geometry={nodes.Green_Blob_0.geometry} material={materials.Green_Main} skeleton={nodes.Green_Blob_0.skeleton} />
              <skinnedMesh name="Green_Blob001_0" geometry={nodes.Green_Blob001_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Green_Blob001_0.skeleton} />
              <skinnedMesh name="Green_Blob001_1" geometry={nodes.Green_Blob001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Green_Blob001_1.skeleton} />
            </group>
            <group name="CharacterArmature040" position={[5.121, -23.336, 0]} rotation={[0, 0, -0.209]} scale={0.826}>
              <primitive object={nodes.CharacterArmature040_rootJoint} />
              <group name="Fish_Blob" />
              <group name="Fish_Blob001" />
              <group name="Fish_Blob002" />
              <skinnedMesh name="Fish_Blob_0" geometry={nodes.Fish_Blob_0.geometry} material={materials.Fish_Main} skeleton={nodes.Fish_Blob_0.skeleton} />
              <skinnedMesh name="Fish_Blob_1" geometry={nodes.Fish_Blob_1.geometry} material={materials.Fish_Secondary} skeleton={nodes.Fish_Blob_1.skeleton} />
              <skinnedMesh name="Fish_Blob_2" geometry={nodes.Fish_Blob_2.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Fish_Blob_2.skeleton} />
              <skinnedMesh name="Fish_Blob_3" geometry={nodes.Fish_Blob_3.geometry} material={materials.Pink_Secondary} skeleton={nodes.Fish_Blob_3.skeleton} />
              <skinnedMesh name="Fish_Blob001_0" geometry={nodes.Fish_Blob001_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Fish_Blob001_0.skeleton} />
              <skinnedMesh name="Fish_Blob001_1" geometry={nodes.Fish_Blob001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Fish_Blob001_1.skeleton} />
              <skinnedMesh name="Fish_Blob002_0" geometry={nodes.Fish_Blob002_0.geometry} material={materials['Eye_White.039']} skeleton={nodes.Fish_Blob002_0.skeleton} />
            </group>
            <group name="CharacterArmature038" position={[-7.462, -23.519, 0]} rotation={[0, 0, 0.27]} scale={0.804}>
              <primitive object={nodes.CharacterArmature038_rootJoint} />
              <group name="Cat_Blob" />
              <skinnedMesh name="Cat_Blob_0" geometry={nodes.Cat_Blob_0.geometry} material={materials.Dog_Main} skeleton={nodes.Cat_Blob_0.skeleton} />
              <skinnedMesh name="Cat_Blob_1" geometry={nodes.Cat_Blob_1.geometry} material={materials.Cat_Secondary} skeleton={nodes.Cat_Blob_1.skeleton} />
              <skinnedMesh name="Cat_Blob_2" geometry={nodes.Cat_Blob_2.geometry} material={materials.Squidle_Main} skeleton={nodes.Cat_Blob_2.skeleton} />
              <skinnedMesh name="Cat_Blob_3" geometry={nodes.Cat_Blob_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Cat_Blob_3.skeleton} />
              <skinnedMesh name="Cat_Blob_4" geometry={nodes.Cat_Blob_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Cat_Blob_4.skeleton} />
            </group>
            <group name="CharacterArmature037" position={[-7.414, -14.783, 0.012]} rotation={[0, 0, 0.235]} scale={0.584}>
              <primitive object={nodes.CharacterArmature037_rootJoint} />
              <group name="Alien_Blob" />
              <group name="Alien_Blob001" />
              <skinnedMesh name="Alien_Blob_0" geometry={nodes.Alien_Blob_0.geometry} material={materials.Alien_Main} skeleton={nodes.Alien_Blob_0.skeleton} />
              <skinnedMesh name="Alien_Blob_1" geometry={nodes.Alien_Blob_1.geometry} material={materials['Alien_Secondary.001']} skeleton={nodes.Alien_Blob_1.skeleton} />
              <skinnedMesh name="Alien_Blob001_0" geometry={nodes.Alien_Blob001_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Alien_Blob001_0.skeleton} />
              <skinnedMesh name="Alien_Blob001_1" geometry={nodes.Alien_Blob001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Alien_Blob001_1.skeleton} />
            </group>
            <group name="CharacterArmature036" position={[6.39, -16.537, -0.038]} rotation={[0, 0, -0.268]} scale={0.897}>
              <primitive object={nodes.CharacterArmature036_rootJoint} />
              <group name="Orc_Skull" />
              <group name="Orc_Weapon001" position={[1.919, -0.069, 1.78]} />
              <skinnedMesh name="Orc_Skull_0" geometry={nodes.Orc_Skull_0.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Orc_Skull_0.skeleton} />
              <skinnedMesh name="Orc_Skull_1" geometry={nodes.Orc_Skull_1.geometry} material={materials.Monkroose_Ears} skeleton={nodes.Orc_Skull_1.skeleton} />
              <skinnedMesh name="Orc_Skull_2" geometry={nodes.Orc_Skull_2.geometry} material={materials.Squidle_Main} skeleton={nodes.Orc_Skull_2.skeleton} />
              <skinnedMesh name="Orc_Skull_3" geometry={nodes.Orc_Skull_3.geometry} material={materials.Orc_Secondary} skeleton={nodes.Orc_Skull_3.skeleton} />
              <skinnedMesh name="Orc_Skull_4" geometry={nodes.Orc_Skull_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Orc_Skull_4.skeleton} />
              <skinnedMesh name="Orc_Skull_5" geometry={nodes.Orc_Skull_5.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Orc_Skull_5.skeleton} />
              <skinnedMesh name="Orc_Weapon001_0" geometry={nodes.Orc_Weapon001_0.geometry} material={materials['Wood.002']} skeleton={nodes.Orc_Weapon001_0.skeleton} />
              <skinnedMesh name="Orc_Weapon001_1" geometry={nodes.Orc_Weapon001_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Orc_Weapon001_1.skeleton} />
            </group>
            <group name="CharacterArmature035" position={[-5.543, -13.471, 0.597]} rotation={[0, 0, 0.195]}>
              <primitive object={nodes.CharacterArmature035_rootJoint} />
              <group name="Ninja" />
              <skinnedMesh name="Ninja_0" geometry={nodes.Ninja_0.geometry} material={materials['Ninja_Main.001']} skeleton={nodes.Ninja_0.skeleton} />
              <skinnedMesh name="Ninja_1" geometry={nodes.Ninja_1.geometry} material={materials.Ninja_Secondary} skeleton={nodes.Ninja_1.skeleton} />
              <skinnedMesh name="Ninja_2" geometry={nodes.Ninja_2.geometry} material={materials['Belt.001']} skeleton={nodes.Ninja_2.skeleton} />
              <skinnedMesh name="Ninja_3" geometry={nodes.Ninja_3.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Ninja_3.skeleton} />
              <skinnedMesh name="Ninja_4" geometry={nodes.Ninja_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Ninja_4.skeleton} />
              <skinnedMesh name="Ninja_5" geometry={nodes.Ninja_5.geometry} material={materials['Eye_White.039']} skeleton={nodes.Ninja_5.skeleton} />
              <skinnedMesh name="Ninja_6" geometry={nodes.Ninja_6.geometry} material={materials['Birb_Secondary.002']} skeleton={nodes.Ninja_6.skeleton} />
            </group>
            <group name="CharacterArmature034" position={[-0.763, -13.666, -0.207]}>
              <primitive object={nodes.CharacterArmature034_rootJoint} />
              <group name="Cactoro" scale={0.54} />
              <skinnedMesh name="Cactoro_0" geometry={nodes.Cactoro_0.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Cactoro_0.skeleton} />
              <skinnedMesh name="Cactoro_1" geometry={nodes.Cactoro_1.geometry} material={materials.Monkroose_Secondary} skeleton={nodes.Cactoro_1.skeleton} />
              <skinnedMesh name="Cactoro_2" geometry={nodes.Cactoro_2.geometry} material={materials.Dino_Tongue} skeleton={nodes.Cactoro_2.skeleton} />
              <skinnedMesh name="Cactoro_3" geometry={nodes.Cactoro_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Cactoro_3.skeleton} />
              <skinnedMesh name="Cactoro_4" geometry={nodes.Cactoro_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Cactoro_4.skeleton} />
              <skinnedMesh name="Cactoro_5" geometry={nodes.Cactoro_5.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Cactoro_5.skeleton} />
            </group>
            <group name="CharacterArmature033" position={[6.159, 2.655, -0.01]} rotation={[0, 0, -0.316]}>
              <primitive object={nodes.CharacterArmature033_rootJoint} />
              <group name="Bunny" />
              <group name="Carrot" position={[0.011, -0.101, 0]} />
              <skinnedMesh name="Bunny_0" geometry={nodes.Bunny_0.geometry} material={materials.Bunny_Main} skeleton={nodes.Bunny_0.skeleton} />
              <skinnedMesh name="Bunny_1" geometry={nodes.Bunny_1.geometry} material={materials.Bunny_Secondary} skeleton={nodes.Bunny_1.skeleton} />
              <skinnedMesh name="Bunny_2" geometry={nodes.Bunny_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Bunny_2.skeleton} />
              <skinnedMesh name="Bunny_3" geometry={nodes.Bunny_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Bunny_3.skeleton} />
              <skinnedMesh name="Carrot_0" geometry={nodes.Carrot_0.geometry} material={materials['Material.024']} skeleton={nodes.Carrot_0.skeleton} />
              <skinnedMesh name="Carrot_1" geometry={nodes.Carrot_1.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Carrot_1.skeleton} />
            </group>
            <group name="CharacterArmature032" position={[-9.13, -7.169, -0.003]} rotation={[0, 0, 0.269]} scale={0.886}>
              <primitive object={nodes.CharacterArmature032_rootJoint} />
              <group name="BlueDemon" scale={0.54} />
              <skinnedMesh name="BlueDemon_0" geometry={nodes.BlueDemon_0.geometry} material={materials.BlueDemon_Main} skeleton={nodes.BlueDemon_0.skeleton} />
              <skinnedMesh name="BlueDemon_1" geometry={nodes.BlueDemon_1.geometry} material={materials.Alpaking_Main} skeleton={nodes.BlueDemon_1.skeleton} />
              <skinnedMesh name="BlueDemon_2" geometry={nodes.BlueDemon_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.BlueDemon_2.skeleton} />
              <skinnedMesh name="BlueDemon_3" geometry={nodes.BlueDemon_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.BlueDemon_3.skeleton} />
              <skinnedMesh name="BlueDemon_4" geometry={nodes.BlueDemon_4.geometry} material={materials['Wood.002']} skeleton={nodes.BlueDemon_4.skeleton} />
              <skinnedMesh name="BlueDemon_5" geometry={nodes.BlueDemon_5.geometry} material={materials['Eye_White.039']} skeleton={nodes.BlueDemon_5.skeleton} />
            </group>
            <group name="CharacterArmature031" position={[-4.195, -1.931, -0.025]} rotation={[0, 0, 0.245]}>
              <primitive object={nodes.CharacterArmature031_rootJoint} />
              <group name="Birb" scale={0.54} />
              <skinnedMesh name="Birb_0" geometry={nodes.Birb_0.geometry} material={materials.Birb_Main} skeleton={nodes.Birb_0.skeleton} />
              <skinnedMesh name="Birb_1" geometry={nodes.Birb_1.geometry} material={materials['Birb_Secondary.002']} skeleton={nodes.Birb_1.skeleton} />
              <skinnedMesh name="Birb_2" geometry={nodes.Birb_2.geometry} material={materials.Chicken_Red} skeleton={nodes.Birb_2.skeleton} />
              <skinnedMesh name="Birb_3" geometry={nodes.Birb_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Birb_3.skeleton} />
              <skinnedMesh name="Birb_4" geometry={nodes.Birb_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Birb_4.skeleton} />
            </group>
            <group name="CharacterArmature030" position={[4.263, 0.338, -0.015]} rotation={[0, 0, -0.132]}>
              <primitive object={nodes.CharacterArmature030_rootJoint} />
              <group name="Alien" />
              <skinnedMesh name="Alien_0" geometry={nodes.Alien_0.geometry} material={materials.Alien_Main} skeleton={nodes.Alien_0.skeleton} />
              <skinnedMesh name="Alien_1" geometry={nodes.Alien_1.geometry} material={materials['Alien_Secondary.001']} skeleton={nodes.Alien_1.skeleton} />
              <skinnedMesh name="Alien_2" geometry={nodes.Alien_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Alien_2.skeleton} />
              <skinnedMesh name="Alien_3" geometry={nodes.Alien_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Alien_3.skeleton} />
              <skinnedMesh name="Alien_4" geometry={nodes.Alien_4.geometry} material={materials.Pink_Secondary} skeleton={nodes.Alien_4.skeleton} />
            </group>
            <group name="CharacterArmature029" position={[-8.161, 10.195, 1.501]} rotation={[0, 0, 0.263]} scale={0.797}>
              <primitive object={nodes.CharacterArmature029_rootJoint} />
              <group name="Tribal_Flying" />
              <skinnedMesh name="Tribal_Flying_0" geometry={nodes.Tribal_Flying_0.geometry} material={materials.Tribal_Main} skeleton={nodes.Tribal_Flying_0.skeleton} />
              <skinnedMesh name="Tribal_Flying_1" geometry={nodes.Tribal_Flying_1.geometry} material={materials['Tribal_Secondary.001']} skeleton={nodes.Tribal_Flying_1.skeleton} />
              <skinnedMesh name="Tribal_Flying_2" geometry={nodes.Tribal_Flying_2.geometry} material={materials.Alpaking_Main} skeleton={nodes.Tribal_Flying_2.skeleton} />
              <skinnedMesh name="Tribal_Flying_3" geometry={nodes.Tribal_Flying_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Tribal_Flying_3.skeleton} />
              <skinnedMesh name="Tribal_Flying_4" geometry={nodes.Tribal_Flying_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Tribal_Flying_4.skeleton} />
            </group>
            <group name="CharacterArmature028" position={[5.482, 4.627, 1.756]} rotation={[0, 0, -0.198]} scale={0.735}>
              <primitive object={nodes.CharacterArmature028_rootJoint} />
              <group name="Squidle002" scale={0.76} />
              <skinnedMesh name="Squidle002_0" geometry={nodes.Squidle002_0.geometry} material={materials.Squidle_Main} skeleton={nodes.Squidle002_0.skeleton} />
              <skinnedMesh name="Squidle002_1" geometry={nodes.Squidle002_1.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Squidle002_1.skeleton} />
              <skinnedMesh name="Squidle002_2" geometry={nodes.Squidle002_2.geometry} material={materials.Pink_Secondary} skeleton={nodes.Squidle002_2.skeleton} />
              <skinnedMesh name="Squidle002_3" geometry={nodes.Squidle002_3.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Squidle002_3.skeleton} />
              <skinnedMesh name="Squidle002_4" geometry={nodes.Squidle002_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Squidle002_4.skeleton} />
              <skinnedMesh name="Squidle002_5" geometry={nodes.Squidle002_5.geometry} material={materials['Eye_White.039']} skeleton={nodes.Squidle002_5.skeleton} />
            </group>
            <group name="CharacterArmature027" position={[1.679, -1.156, 3.693]} scale={0.951}>
              <primitive object={nodes.CharacterArmature027_rootJoint} />
              <group name="Pigeon" />
              <skinnedMesh name="Pigeon_0" geometry={nodes.Pigeon_0.geometry} material={materials['Pigeon_Main.001']} skeleton={nodes.Pigeon_0.skeleton} />
              <skinnedMesh name="Pigeon_1" geometry={nodes.Pigeon_1.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Pigeon_1.skeleton} />
              <skinnedMesh name="Pigeon_2" geometry={nodes.Pigeon_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Pigeon_2.skeleton} />
              <skinnedMesh name="Pigeon_3" geometry={nodes.Pigeon_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Pigeon_3.skeleton} />
            </group>
            <group name="CharacterArmature" position={[3.814, 7.994, 1.421]} rotation={[0, 0, -0.1]} scale={0.885}>
              <primitive object={nodes.CharacterArmature_rootJoint} />
              <group name="Ghost_Skull" />
              <skinnedMesh name="Ghost_Skull_0" geometry={nodes.Ghost_Skull_0.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Ghost_Skull_0.skeleton} />
              <skinnedMesh name="Ghost_Skull_1" geometry={nodes.Ghost_Skull_1.geometry} material={materials['Ghost_Main.001']} skeleton={nodes.Ghost_Skull_1.skeleton} />
            </group>
            <group name="CharacterArmature025" position={[1.432, -24.349, 0]} rotation={[0, 0, -0.341]} scale={0.96}>
              <primitive object={nodes.CharacterArmature025_rootJoint} />
              <group name="Chicken_Blob" />
              <skinnedMesh name="Chicken_Blob_0" geometry={nodes.Chicken_Blob_0.geometry} material={materials.Chicken_Main} skeleton={nodes.Chicken_Blob_0.skeleton} />
              <skinnedMesh name="Chicken_Blob_1" geometry={nodes.Chicken_Blob_1.geometry} material={materials.Chicken_Red} skeleton={nodes.Chicken_Blob_1.skeleton} />
              <skinnedMesh name="Chicken_Blob_2" geometry={nodes.Chicken_Blob_2.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Chicken_Blob_2.skeleton} />
              <skinnedMesh name="Chicken_Blob_3" geometry={nodes.Chicken_Blob_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Chicken_Blob_3.skeleton} />
              <skinnedMesh name="Chicken_Blob_4" geometry={nodes.Chicken_Blob_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Chicken_Blob_4.skeleton} />
            </group>
            <group name="CharacterArmature024" position={[-0.735, -23.673, 0]} rotation={[0, 0, 0.124]} scale={0.565}>
              <primitive object={nodes.CharacterArmature024_rootJoint} />
              <group name="Cactoro_Blob" />
              <group name="Cactoro_Blob001" />
              <skinnedMesh name="Cactoro_Blob_0" geometry={nodes.Cactoro_Blob_0.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Cactoro_Blob_0.skeleton} />
              <skinnedMesh name="Cactoro_Blob_1" geometry={nodes.Cactoro_Blob_1.geometry} material={materials.Monkroose_Secondary} skeleton={nodes.Cactoro_Blob_1.skeleton} />
              <skinnedMesh name="Cactoro_Blob001_0" geometry={nodes.Cactoro_Blob001_0.geometry} material={materials['Cactoro_Main.002']} skeleton={nodes.Cactoro_Blob001_0.skeleton} />
              <skinnedMesh name="Cactoro_Blob001_1" geometry={nodes.Cactoro_Blob001_1.geometry} material={materials.Monkroose_Secondary} skeleton={nodes.Cactoro_Blob001_1.skeleton} />
              <skinnedMesh name="Cactoro_Blob001_2" geometry={nodes.Cactoro_Blob001_2.geometry} material={materials.Dino_Tongue} skeleton={nodes.Cactoro_Blob001_2.skeleton} />
              <skinnedMesh name="Cactoro_Blob001_3" geometry={nodes.Cactoro_Blob001_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Cactoro_Blob001_3.skeleton} />
              <skinnedMesh name="Cactoro_Blob001_4" geometry={nodes.Cactoro_Blob001_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Cactoro_Blob001_4.skeleton} />
            </group>
            <group name="CharacterArmature023" position={[-7.172, -3.45, 0]} rotation={[0, 0, 0.256]} scale={0.703}>
              <primitive object={nodes.CharacterArmature023_rootJoint} />
              <group name="Birb_Blob" />
              <skinnedMesh name="Birb_Blob_0" geometry={nodes.Birb_Blob_0.geometry} material={materials.Birb_Main} skeleton={nodes.Birb_Blob_0.skeleton} />
              <skinnedMesh name="Birb_Blob_1" geometry={nodes.Birb_Blob_1.geometry} material={materials.Chicken_Red} skeleton={nodes.Birb_Blob_1.skeleton} />
              <skinnedMesh name="Birb_Blob_2" geometry={nodes.Birb_Blob_2.geometry} material={materials['Birb_Secondary.002']} skeleton={nodes.Birb_Blob_2.skeleton} />
              <skinnedMesh name="Birb_Blob_3" geometry={nodes.Birb_Blob_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Birb_Blob_3.skeleton} />
              <skinnedMesh name="Birb_Blob_4" geometry={nodes.Birb_Blob_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Birb_Blob_4.skeleton} />
            </group>
            <group name="CharacterArmature022" position={[-5.941, 8.824, 1.127]} rotation={[0, 0, 0.221]} scale={0.904}>
              <primitive object={nodes.CharacterArmature022_rootJoint} />
              <group name="Hywirl" />
              <skinnedMesh name="Hywirl_0" geometry={nodes.Hywirl_0.geometry} material={materials.Hywirl_Main} skeleton={nodes.Hywirl_0.skeleton} />
              <skinnedMesh name="Hywirl_1" geometry={nodes.Hywirl_1.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Hywirl_1.skeleton} />
              <skinnedMesh name="Hywirl_2" geometry={nodes.Hywirl_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Hywirl_2.skeleton} />
            </group>
            <group name="CharacterArmature021" position={[-1.68, 3.205, -0.992]} rotation={[0, 0, 0.12]} scale={1.017}>
              <primitive object={nodes.CharacterArmature021_rootJoint} />
              <group name="Goleling_Evolved" />
              <skinnedMesh name="Goleling_Evolved_0" geometry={nodes.Goleling_Evolved_0.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Goleling_Evolved_0.skeleton} />
              <skinnedMesh name="Goleling_Evolved_1" geometry={nodes.Goleling_Evolved_1.geometry} material={materials.Pink_Secondary} skeleton={nodes.Goleling_Evolved_1.skeleton} />
              <skinnedMesh name="Goleling_Evolved_2" geometry={nodes.Goleling_Evolved_2.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Goleling_Evolved_2.skeleton} />
              <skinnedMesh name="Goleling_Evolved_3" geometry={nodes.Goleling_Evolved_3.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Goleling_Evolved_3.skeleton} />
              <skinnedMesh name="Goleling_Evolved_4" geometry={nodes.Goleling_Evolved_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Goleling_Evolved_4.skeleton} />
              <skinnedMesh name="Goleling_Evolved_5" geometry={nodes.Goleling_Evolved_5.geometry} material={materials['Eye_White.039']} skeleton={nodes.Goleling_Evolved_5.skeleton} />
            </group>
            <group name="CharacterArmature020" position={[-4.871, 3.93, 3.382]} rotation={[0, 0, 0.197]} scale={0.81}>
              <primitive object={nodes.CharacterArmature020_rootJoint} />
              <group name="Goleling" />
              <skinnedMesh name="Goleling_0" geometry={nodes.Goleling_0.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Goleling_0.skeleton} />
              <skinnedMesh name="Goleling_1" geometry={nodes.Goleling_1.geometry} material={materials.Pink_Secondary} skeleton={nodes.Goleling_1.skeleton} />
              <skinnedMesh name="Goleling_2" geometry={nodes.Goleling_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Goleling_2.skeleton} />
              <skinnedMesh name="Goleling_3" geometry={nodes.Goleling_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Goleling_3.skeleton} />
            </group>
            <group name="CharacterArmature019" position={[-8.731, 7.445, -0.277]} rotation={[0, 0, 0.291]} scale={0.865}>
              <primitive object={nodes.CharacterArmature019_rootJoint} />
              <group name="Glub_Evolved" scale={0.76} />
              <skinnedMesh name="Glub_Evolved_0" geometry={nodes.Glub_Evolved_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Glub_Evolved_0.skeleton} />
              <skinnedMesh name="Glub_Evolved_1" geometry={nodes.Glub_Evolved_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Glub_Evolved_1.skeleton} />
              <skinnedMesh name="Glub_Evolved_2" geometry={nodes.Glub_Evolved_2.geometry} material={materials.Glub_Main} skeleton={nodes.Glub_Evolved_2.skeleton} />
              <skinnedMesh name="Glub_Evolved_3" geometry={nodes.Glub_Evolved_3.geometry} material={materials['Wings.004']} skeleton={nodes.Glub_Evolved_3.skeleton} />
            </group>
            <group name="CharacterArmature018" position={[-5.775, 3.376, -0.508]} rotation={[0, 0, 0.344]} scale={0.757}>
              <primitive object={nodes.CharacterArmature018_rootJoint} />
              <group name="Glub" />
              <skinnedMesh name="Glub_0" geometry={nodes.Glub_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Glub_0.skeleton} />
              <skinnedMesh name="Glub_1" geometry={nodes.Glub_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Glub_1.skeleton} />
              <skinnedMesh name="Glub_2" geometry={nodes.Glub_2.geometry} material={materials.Glub_Main} skeleton={nodes.Glub_2.skeleton} />
              <skinnedMesh name="Glub_3" geometry={nodes.Glub_3.geometry} material={materials['Wings.004']} skeleton={nodes.Glub_3.skeleton} />
            </group>
            <group name="CharacterArmature017" position={[-3.834, 8.162, 0.763]} rotation={[0, 0, 0.198]} scale={0.883}>
              <primitive object={nodes.CharacterArmature017_rootJoint} />
              <group name="Ghost" />
              <skinnedMesh name="Ghost_0" geometry={nodes.Ghost_0.geometry} material={materials['Ghost_Main.001']} skeleton={nodes.Ghost_0.skeleton} />
              <skinnedMesh name="Ghost_1" geometry={nodes.Ghost_1.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Ghost_1.skeleton} />
              <skinnedMesh name="Ghost_2" geometry={nodes.Ghost_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Ghost_2.skeleton} />
            </group>
            <group name="CharacterArmature015" position={[-3.177, 10.147, 1.611]} rotation={[0, 0, 0.241]} scale={0.765}>
              <primitive object={nodes.CharacterArmature015_rootJoint} />
              <group name="Dragon_Fly" />
              <skinnedMesh name="Dragon_Fly_0" geometry={nodes.Dragon_Fly_0.geometry} material={materials['Dragon_Main.001']} skeleton={nodes.Dragon_Fly_0.skeleton} />
              <skinnedMesh name="Dragon_Fly_1" geometry={nodes.Dragon_Fly_1.geometry} material={materials.Pink_Secondary} skeleton={nodes.Dragon_Fly_1.skeleton} />
              <skinnedMesh name="Dragon_Fly_2" geometry={nodes.Dragon_Fly_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dragon_Fly_2.skeleton} />
              <skinnedMesh name="Dragon_Fly_3" geometry={nodes.Dragon_Fly_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Dragon_Fly_3.skeleton} />
              <skinnedMesh name="Dragon_Fly_4" geometry={nodes.Dragon_Fly_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dragon_Fly_4.skeleton} />
            </group>
            <group name="CharacterArmature013" position={[7.86, 1.368, 2.244]} rotation={[0, 0, -0.357]} scale={0.809}>
              <primitive object={nodes.CharacterArmature013_rootJoint} />
              <group name="Armabee_Evolved" />
              <skinnedMesh name="Armabee_Evolved_0" geometry={nodes.Armabee_Evolved_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Armabee_Evolved_0.skeleton} />
              <skinnedMesh name="Armabee_Evolved_1" geometry={nodes.Armabee_Evolved_1.geometry} material={materials.Alpaking_Main} skeleton={nodes.Armabee_Evolved_1.skeleton} />
              <skinnedMesh name="Armabee_Evolved_2" geometry={nodes.Armabee_Evolved_2.geometry} material={materials.Pink_Secondary} skeleton={nodes.Armabee_Evolved_2.skeleton} />
              <skinnedMesh name="Armabee_Evolved_3" geometry={nodes.Armabee_Evolved_3.geometry} material={materials['Teeth.002']} skeleton={nodes.Armabee_Evolved_3.skeleton} />
              <skinnedMesh name="Armabee_Evolved_4" geometry={nodes.Armabee_Evolved_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Armabee_Evolved_4.skeleton} />
              <skinnedMesh name="Armabee_Evolved_5" geometry={nodes.Armabee_Evolved_5.geometry} material={materials['Eye_White.039']} skeleton={nodes.Armabee_Evolved_5.skeleton} />
              <skinnedMesh name="Armabee_Evolved_6" geometry={nodes.Armabee_Evolved_6.geometry} material={materials['Wings.004']} skeleton={nodes.Armabee_Evolved_6.skeleton} />
            </group>
            <group name="CharacterArmature012" position={[5.531, 3.735, 3.251]} rotation={[0, 0, -0.134]} scale={0.809}>
              <primitive object={nodes.CharacterArmature012_rootJoint} />
              <group name="Armabee" />
              <skinnedMesh name="Armabee_0" geometry={nodes.Armabee_0.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Armabee_0.skeleton} />
              <skinnedMesh name="Armabee_1" geometry={nodes.Armabee_1.geometry} material={materials.Alpaking_Main} skeleton={nodes.Armabee_1.skeleton} />
              <skinnedMesh name="Armabee_2" geometry={nodes.Armabee_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Armabee_2.skeleton} />
              <skinnedMesh name="Armabee_3" geometry={nodes.Armabee_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Armabee_3.skeleton} />
              <skinnedMesh name="Armabee_4" geometry={nodes.Armabee_4.geometry} material={materials['Wings.004']} skeleton={nodes.Armabee_4.skeleton} />
            </group>
            <group name="CharacterArmature011" position={[1.138, 3.517, 1.027]} scale={0.801}>
              <primitive object={nodes.CharacterArmature011_rootJoint} />
              <group name="Alpaking_Evolved" />
              <skinnedMesh name="Alpaking_Evolved_0" geometry={nodes.Alpaking_Evolved_0.geometry} material={materials.Alpaking_Main} skeleton={nodes.Alpaking_Evolved_0.skeleton} />
              <skinnedMesh name="Alpaking_Evolved_1" geometry={nodes.Alpaking_Evolved_1.geometry} material={materials.Monkroose_Ears} skeleton={nodes.Alpaking_Evolved_1.skeleton} />
              <skinnedMesh name="Alpaking_Evolved_2" geometry={nodes.Alpaking_Evolved_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Alpaking_Evolved_2.skeleton} />
              <skinnedMesh name="Alpaking_Evolved_3" geometry={nodes.Alpaking_Evolved_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Alpaking_Evolved_3.skeleton} />
              <skinnedMesh name="Alpaking_Evolved_4" geometry={nodes.Alpaking_Evolved_4.geometry} material={materials['Wings.004']} skeleton={nodes.Alpaking_Evolved_4.skeleton} />
            </group>
            <group name="CharacterArmature010" position={[2.445, 8.6, 1.235]} rotation={[0, 0, -0.116]} scale={0.72}>
              <primitive object={nodes.CharacterArmature010_rootJoint} />
              <group name="Alpaking" />
              <skinnedMesh name="Alpaking_0" geometry={nodes.Alpaking_0.geometry} material={materials.Alpaking_Main} skeleton={nodes.Alpaking_0.skeleton} />
              <skinnedMesh name="Alpaking_1" geometry={nodes.Alpaking_1.geometry} material={materials.Monkroose_Ears} skeleton={nodes.Alpaking_1.skeleton} />
              <skinnedMesh name="Alpaking_2" geometry={nodes.Alpaking_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Alpaking_2.skeleton} />
              <skinnedMesh name="Alpaking_3" geometry={nodes.Alpaking_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Alpaking_3.skeleton} />
              <skinnedMesh name="Alpaking_4" geometry={nodes.Alpaking_4.geometry} material={materials['Wings.004']} skeleton={nodes.Alpaking_4.skeleton} />
            </group>
            <group name="CharacterArmature009" position={[-3.667, -14.389, 0]} rotation={[0, 0, 0.161]}>
              <primitive object={nodes.CharacterArmature009_rootJoint} />
              <group name="Yeti" />
              <skinnedMesh name="Yeti_0" geometry={nodes.Yeti_0.geometry} material={materials.Chicken_Main} skeleton={nodes.Yeti_0.skeleton} />
              <skinnedMesh name="Yeti_1" geometry={nodes.Yeti_1.geometry} material={materials.Yeti_Secondary} skeleton={nodes.Yeti_1.skeleton} />
              <skinnedMesh name="Yeti_2" geometry={nodes.Yeti_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Yeti_2.skeleton} />
              <skinnedMesh name="Yeti_3" geometry={nodes.Yeti_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Yeti_3.skeleton} />
              <skinnedMesh name="Yeti_4" geometry={nodes.Yeti_4.geometry} material={materials['Teeth.002']} skeleton={nodes.Yeti_4.skeleton} />
              <skinnedMesh name="Yeti_5" geometry={nodes.Yeti_5.geometry} material={materials.Pink_Secondary} skeleton={nodes.Yeti_5.skeleton} />
            </group>
            <group name="CharacterArmature008" position={[8.407, -13.754, 0]} rotation={[0, 0, -0.432]} scale={0.853}>
              <primitive object={nodes.CharacterArmature008_rootJoint} />
              <group name="Orc" />
              <group name="Orc_Weapon" position={[1.884, 0.077, 1.748]} />
              <skinnedMesh name="Orc_0" geometry={nodes.Orc_0.geometry} material={materials['Orc_Main.002']} skeleton={nodes.Orc_0.skeleton} />
              <skinnedMesh name="Orc_1" geometry={nodes.Orc_1.geometry} material={materials.Orc_Secondary} skeleton={nodes.Orc_1.skeleton} />
              <skinnedMesh name="Orc_2" geometry={nodes.Orc_2.geometry} material={materials.Monkroose_Ears} skeleton={nodes.Orc_2.skeleton} />
              <skinnedMesh name="Orc_3" geometry={nodes.Orc_3.geometry} material={materials.Squidle_Main} skeleton={nodes.Orc_3.skeleton} />
              <skinnedMesh name="Orc_4" geometry={nodes.Orc_4.geometry} material={materials.Pink_Secondary} skeleton={nodes.Orc_4.skeleton} />
              <skinnedMesh name="Orc_5" geometry={nodes.Orc_5.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Orc_5.skeleton} />
              <skinnedMesh name="Orc_6" geometry={nodes.Orc_6.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Orc_6.skeleton} />
              <skinnedMesh name="Orc_7" geometry={nodes.Orc_7.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Orc_7.skeleton} />
              <skinnedMesh name="Orc_8" geometry={nodes.Orc_8.geometry} material={materials['Eye_White.039']} skeleton={nodes.Orc_8.skeleton} />
              <skinnedMesh name="Orc_Weapon_0" geometry={nodes.Orc_Weapon_0.geometry} material={materials['Wood.002']} skeleton={nodes.Orc_Weapon_0.skeleton} />
              <skinnedMesh name="Orc_Weapon_1" geometry={nodes.Orc_Weapon_1.geometry} material={materials['Eye_White.039']} skeleton={nodes.Orc_Weapon_1.skeleton} />
            </group>
            <group name="CharacterArmature007" position={[2.428, -5.001, 0]} rotation={[0, 0, -0.075]} scale={1.089}>
              <primitive object={nodes.CharacterArmature007_rootJoint} />
              <group name="Mushroom" position={[1.93, 0.227, 1.76]} />
              <group name="MushroomKing" />
              <skinnedMesh name="Mushroom_0" geometry={nodes.Mushroom_0.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Mushroom_0.skeleton} />
              <skinnedMesh name="Mushroom_1" geometry={nodes.Mushroom_1.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Mushroom_1.skeleton} />
              <skinnedMesh name="MushroomKing_0" geometry={nodes.MushroomKing_0.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.MushroomKing_0.skeleton} />
              <skinnedMesh name="MushroomKing_1" geometry={nodes.MushroomKing_1.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.MushroomKing_1.skeleton} />
              <skinnedMesh name="MushroomKing_2" geometry={nodes.MushroomKing_2.geometry} material={materials['Orc_Main.002']} skeleton={nodes.MushroomKing_2.skeleton} />
              <skinnedMesh name="MushroomKing_3" geometry={nodes.MushroomKing_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.MushroomKing_3.skeleton} />
              <skinnedMesh name="MushroomKing_4" geometry={nodes.MushroomKing_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.MushroomKing_4.skeleton} />
            </group>
            <group name="CharacterArmature006" position={[-7.577, 5.472, 0]} rotation={[0, 0, 0.248]} scale={0.917}>
              <primitive object={nodes.CharacterArmature006_rootJoint} />
              <group name="Monkroose" />
              <skinnedMesh name="Monkroose_0" geometry={nodes.Monkroose_0.geometry} material={materials.Monkroose_Main} skeleton={nodes.Monkroose_0.skeleton} />
              <skinnedMesh name="Monkroose_1" geometry={nodes.Monkroose_1.geometry} material={materials.Monkroose_Secondary} skeleton={nodes.Monkroose_1.skeleton} />
              <skinnedMesh name="Monkroose_2" geometry={nodes.Monkroose_2.geometry} material={materials.Monkroose_Ears} skeleton={nodes.Monkroose_2.skeleton} />
              <skinnedMesh name="Monkroose_3" geometry={nodes.Monkroose_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Monkroose_3.skeleton} />
              <skinnedMesh name="Monkroose_4" geometry={nodes.Monkroose_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Monkroose_4.skeleton} />
            </group>
            <group name="CharacterArmature005" position={[-2.716, -7.119, 0]} rotation={[0, 0, 0.195]} scale={1.029}>
              <primitive object={nodes.CharacterArmature005_rootJoint} />
              <group name="Frog" />
              <skinnedMesh name="Frog_0" geometry={nodes.Frog_0.geometry} material={materials.Frog_Main} skeleton={nodes.Frog_0.skeleton} />
              <skinnedMesh name="Frog_1" geometry={nodes.Frog_1.geometry} material={materials.Frog_Secondary} skeleton={nodes.Frog_1.skeleton} />
              <skinnedMesh name="Frog_2" geometry={nodes.Frog_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Frog_2.skeleton} />
              <skinnedMesh name="Frog_3" geometry={nodes.Frog_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Frog_3.skeleton} />
            </group>
            <group name="CharacterArmature004" position={[7.604, -1.604, 0]} rotation={[0, 0, -0.186]} scale={0.829}>
              <primitive object={nodes.CharacterArmature004_rootJoint} />
              <group name="Fish" />
              <skinnedMesh name="Fish_0" geometry={nodes.Fish_0.geometry} material={materials.Fish_Main} skeleton={nodes.Fish_0.skeleton} />
              <skinnedMesh name="Fish_1" geometry={nodes.Fish_1.geometry} material={materials.Fish_Secondary} skeleton={nodes.Fish_1.skeleton} />
              <skinnedMesh name="Fish_2" geometry={nodes.Fish_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Fish_2.skeleton} />
              <skinnedMesh name="Fish_3" geometry={nodes.Fish_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Fish_3.skeleton} />
              <skinnedMesh name="Fish_4" geometry={nodes.Fish_4.geometry} material={materials.Pink_Secondary} skeleton={nodes.Fish_4.skeleton} />
              <skinnedMesh name="Fish_5" geometry={nodes.Fish_5.geometry} material={materials.Pigeon_Secondary} skeleton={nodes.Fish_5.skeleton} />
            </group>
            <group name="CharacterArmature003" position={[6.713, -9.193, 0]} rotation={[0, 0, -0.239]}>
              <primitive object={nodes.CharacterArmature003_rootJoint} />
              <group name="Dino" />
              <skinnedMesh name="Dino_0" geometry={nodes.Dino_0.geometry} material={materials.Dino_Main} skeleton={nodes.Dino_0.skeleton} />
              <skinnedMesh name="Dino_1" geometry={nodes.Dino_1.geometry} material={materials.Alpaking_Main} skeleton={nodes.Dino_1.skeleton} />
              <skinnedMesh name="Dino_2" geometry={nodes.Dino_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Dino_2.skeleton} />
              <skinnedMesh name="Dino_3" geometry={nodes.Dino_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dino_3.skeleton} />
              <skinnedMesh name="Dino_4" geometry={nodes.Dino_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dino_4.skeleton} />
              <skinnedMesh name="Dino_5" geometry={nodes.Dino_5.geometry} material={materials.Dino_Tongue} skeleton={nodes.Dino_5.skeleton} />
            </group>
            <group name="CharacterArmature002" position={[4.45, -12.055, 0]} rotation={[0, 0, -0.34]} scale={0.903}>
              <primitive object={nodes.CharacterArmature002_rootJoint} />
              <group name="Demon" />
              <group name="Trident" position={[1.895, 0.17, 1.734]} rotation={[Math.PI / 2, 0, 0]} scale={0.753} />
              <skinnedMesh name="Demon_0" geometry={nodes.Demon_0.geometry} material={materials.Dino_Tongue} skeleton={nodes.Demon_0.skeleton} />
              <skinnedMesh name="Demon_1" geometry={nodes.Demon_1.geometry} material={materials['Black.001']} skeleton={nodes.Demon_1.skeleton} />
              <skinnedMesh name="Demon_2" geometry={nodes.Demon_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Demon_2.skeleton} />
              <skinnedMesh name="Demon_3" geometry={nodes.Demon_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Demon_3.skeleton} />
              <skinnedMesh name="Trident_0" geometry={nodes.Trident_0.geometry} material={materials['Black.001']} skeleton={nodes.Trident_0.skeleton} />
            </group>
            <group name="CharacterArmature001" position={[1.94, -16.189, 0]} rotation={[0, 0, -0.304]}>
              <primitive object={nodes.CharacterArmature001_rootJoint} />
              <group name="Tribal" />
              <skinnedMesh name="Tribal_0" geometry={nodes.Tribal_0.geometry} material={materials.Tribal_Main} skeleton={nodes.Tribal_0.skeleton} />
              <skinnedMesh name="Tribal_1" geometry={nodes.Tribal_1.geometry} material={materials['Tribal_Secondary.001']} skeleton={nodes.Tribal_1.skeleton} />
              <skinnedMesh name="Tribal_2" geometry={nodes.Tribal_2.geometry} material={materials.Alpaking_Main} skeleton={nodes.Tribal_2.skeleton} />
              <skinnedMesh name="Tribal_3" geometry={nodes.Tribal_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Tribal_3.skeleton} />
              <skinnedMesh name="Tribal_4" geometry={nodes.Tribal_4.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Tribal_4.skeleton} />
            </group>
            <group name="CharacterArmature026" position={[-9.051, -20.576, 0]} rotation={[0, 0, 0.461]} scale={0.62}>
              <primitive object={nodes.CharacterArmature026_rootJoint} />
              <group name="Mushnub_Blob001" />
              <skinnedMesh name="Mushnub_Blob001_0" geometry={nodes.Mushnub_Blob001_0.geometry} material={materials['MushroomKing_Secondary.002']} skeleton={nodes.Mushnub_Blob001_0.skeleton} />
              <skinnedMesh name="Mushnub_Blob001_1" geometry={nodes.Mushnub_Blob001_1.geometry} material={materials['MushroomKing_Main.002']} skeleton={nodes.Mushnub_Blob001_1.skeleton} />
              <skinnedMesh name="Mushnub_Blob001_2" geometry={nodes.Mushnub_Blob001_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Mushnub_Blob001_2.skeleton} />
              <skinnedMesh name="Mushnub_Blob001_3" geometry={nodes.Mushnub_Blob001_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Mushnub_Blob001_3.skeleton} />
            </group>
            <group name="CharacterArmature039" position={[-5.526, -24.153, 0]} rotation={[0, 0, 0.329]} scale={0.76}>
              <primitive object={nodes.CharacterArmature039_rootJoint} />
              <group name="Dog_Blob" />
              <skinnedMesh name="Dog_Blob_0" geometry={nodes.Dog_Blob_0.geometry} material={materials.Dog_Main} skeleton={nodes.Dog_Blob_0.skeleton} />
              <skinnedMesh name="Dog_Blob_1" geometry={nodes.Dog_Blob_1.geometry} material={materials.Chicken_Main} skeleton={nodes.Dog_Blob_1.skeleton} />
              <skinnedMesh name="Dog_Blob_2" geometry={nodes.Dog_Blob_2.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Dog_Blob_2.skeleton} />
              <skinnedMesh name="Dog_Blob_3" geometry={nodes.Dog_Blob_3.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dog_Blob_3.skeleton} />
            </group>
            <group name="CharacterArmature016" position={[-1.226, 7.58, 1.071]} rotation={[0, 0, 0.103]} scale={0.84}>
              <primitive object={nodes.CharacterArmature016_rootJoint} />
              <group name="Dragon" />
              <skinnedMesh name="Dragon_0" geometry={nodes.Dragon_0.geometry} material={materials['Dragon_Main.001']} skeleton={nodes.Dragon_0.skeleton} />
              <skinnedMesh name="Dragon_1" geometry={nodes.Dragon_1.geometry} material={materials.Pink_Secondary} skeleton={nodes.Dragon_1.skeleton} />
              <skinnedMesh name="Dragon_2" geometry={nodes.Dragon_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dragon_2.skeleton} />
              <skinnedMesh name="Dragon_3" geometry={nodes.Dragon_3.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Dragon_3.skeleton} />
              <skinnedMesh name="Dragon_4" geometry={nodes.Dragon_4.geometry} material={materials['Eye_White.039']} skeleton={nodes.Dragon_4.skeleton} />
            </group>
            <group name="CharacterArmature014" position={[-1.259, -3.781, 5.214]} rotation={[0, 0, 0.105]} scale={0.733}>
              <primitive object={nodes.CharacterArmature014_rootJoint} />
              <group name="Demon_Flying" />
              <group name="Demon_Flying001" />
              <group name="Demon_Flying002" />
              <skinnedMesh name="Demon_Flying_0" geometry={nodes.Demon_Flying_0.geometry} material={materials.Dino_Tongue} skeleton={nodes.Demon_Flying_0.skeleton} />
              <skinnedMesh name="Demon_Flying001_0" geometry={nodes.Demon_Flying001_0.geometry} material={materials['Black.001']} skeleton={nodes.Demon_Flying001_0.skeleton} />
              <skinnedMesh name="Demon_Flying001_1" geometry={nodes.Demon_Flying001_1.geometry} material={materials['Eye_Black.046']} skeleton={nodes.Demon_Flying001_1.skeleton} />
              <skinnedMesh name="Demon_Flying001_2" geometry={nodes.Demon_Flying001_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Demon_Flying001_2.skeleton} />
              <skinnedMesh name="Demon_Flying002_0" geometry={nodes.Demon_Flying002_0.geometry} material={materials.Dino_Tongue} skeleton={nodes.Demon_Flying002_0.skeleton} />
              <skinnedMesh name="Demon_Flying002_1" geometry={nodes.Demon_Flying002_1.geometry} material={materials['Black.001']} skeleton={nodes.Demon_Flying002_1.skeleton} />
              <skinnedMesh name="Demon_Flying002_2" geometry={nodes.Demon_Flying002_2.geometry} material={materials['Eye_White.039']} skeleton={nodes.Demon_Flying002_2.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/monsters.glb')
