/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/building.glb -o src/components/Village/Village.jsx -r public
Author: RyeNguyen (https://sketchfab.com/RyeNguyen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/building-7f75d4f06396447aacd834ccaa3c2615
Title: Building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  default function Model(props) {
  const { nodes, materials } = useGLTF('/models/building.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0,14,0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.038}>
        <mesh geometry={nodes.Cylinder_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.Cylinder_wall_0.geometry} material={materials.wall} />
        <mesh geometry={nodes.Cylinder_wall_dark_0.geometry} material={materials.wall_dark} />
        <mesh geometry={nodes.Cylinder_roof_0.geometry} material={materials.roof} />
        <mesh geometry={nodes.Cylinder_green_0.geometry} material={materials.green} />
        <mesh geometry={nodes.Cylinder_glass_pane_0.geometry} material={materials.glass_pane} />
        <mesh geometry={nodes.Cylinder_grey_0.geometry} material={materials.grey} />
        <mesh geometry={nodes.Cylinder_red_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Cylinder_brown_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cylinder_wood_0.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cylinder_glass_pane_dark_0.geometry} material={materials.glass_pane_dark} />
        <mesh geometry={nodes.Cylinder_red_dark_0.geometry} material={materials.red_dark} />
        <mesh geometry={nodes.Cylinder_grey_light_0.geometry} material={materials.grey_light} />
        <mesh geometry={nodes.Cylinder_grey_dark_0.geometry} material={materials.grey_dark} />
        <mesh geometry={nodes.Cylinder_metallic_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cylinder_black_0.geometry} material={materials.black} />
        <mesh geometry={nodes.Cylinder_green_light_0.geometry} material={materials.green_light} />
        <mesh geometry={nodes.Cylinder_green_tree_dark_0.geometry} material={materials.green_tree_dark} />
        <mesh geometry={nodes.Cylinder_green_tree_light_0.geometry} material={materials.green_tree_light} />
        <mesh geometry={nodes.Cylinder_green_tree__0.geometry} material={materials.green_tree} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/building.glb')
